Port to C++20.
google/s2geometry pull request #106
Opened 2020-05-01 11:42 UTC by gatehouse

This patch replaces various constructs that were deprecated in C++17 and removed in C++20 with their C++20 counterparts.

With this patch, s2geometry can be compiled with gcc 10.

2020-05-07 19:46 UTC, jmr commented
What's the minimum c++ version needed for this to work?

2020-05-14 09:51 UTC, gatehouse commented
> What's the minimum c++ version needed for this to work?
@jmr I would expect this to work from C++14 upwards.

2020-06-11 09:46 UTC, jmr commented
This isn't compiling:

https://travis-ci.org/github/google/s2geometry/builds/696839883

C++20 is too new to require. C++14 is definitely ok and C++17 is probably ok.

2020-08-31 07:08 UTC, jmr commented
> With this patch, s2geometry can be compiled with gcc 10.

gcc 10 works without this patch.
https://travis-ci.org/github/google/s2geometry/jobs/722137049#L423

2020-08-31 07:12 UTC, jmr requested changes

2020-08-31 07:12 UTC, jmr commented on src/s2/base/logging.h
> +  ABSL_ATTRIBUTE_NORETURN ~S2FatalLogMessage() { throw std::runtime_error("s2geometry fatal error"); }
Please separate out changes unrelated to c++17-deprecated interfaces.

2020-08-31 07:12 UTC, jmr commented on src/s2/s2shape_index.h
> -      : public std::iterator<std::forward_iterator_tag, S2Shape*> {
This provided typedefs. Where do they come from now?

2020-08-31 07:12 UTC, jmr commented on CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 20)
You can bump this to 17 if it's really needed to compile any of the replacements.

2020-08-31 07:13 UTC, jmr commented
I will close and re-open this in hope of getting travis-ci to notice the `.travis.yml` changes. The current `CMakeLists.txt` is incompatible with the old `.travis.yml`.

2020-08-31 07:22 UTC, jmr commented
This breaks both compilers that support c++20
https://travis-ci.org/github/google/s2geometry/jobs/722649190#L544

and those that don't
https://travis-ci.org/github/google/s2geometry/jobs/722649187#L324

2024-11-08 09:21 UTC, jmr commented
I think all C++20 problems should have been fixed.  If not, reopen a new issue/PR.

2024-11-08 09:21 UTC, closed without merging