CMake: Use GNUInstallDirs for install destination
google/s2geometry pull request #186
Opened 2021-04-18 18:02 UTC by podsvirov

2021-04-20 08:02 UTC, jmr commented
Can you add something to README.md about how to configure install locations?

2021-04-20 19:02 UTC, podsvirov commented
> Can you add something to README.md about how to configure install locations?

Done. Please review again (sorry for possible  lingual mistakes).

2021-04-22 14:50 UTC, jmr requested changes

2021-04-22 14:50 UTC, jmr commented on README.md
> +_NOTE_: The `uninstall` target missed but `install_manifest.txt` may be helpfull.
How about "there is not `uninstall` target but ..."?

2021-04-22 14:50 UTC, jmr commented on README.md
> +To edit cached variables type:
What are cached variables? I'm not sure this is going to help without further explanation.

2021-04-24 09:38 UTC, merged