Make python optional via flags
google/s2geometry pull request #189
Opened 2021-04-30 21:49 UTC by sammorris81

Add a flag to determine if we should install the Python interface, and add additional python3-dev dependency to the install instructions.

2021-05-04 07:51 UTC, jmr requested changes

2021-05-04 07:51 UTC, jmr commented on CMakeLists.txt
> +  include_directories(
put this on one line since it fits now

2021-05-04 07:51 UTC, jmr commented on README.md
>  If you want the Python interface, you will also need:
you'll also need to run cmake with -DWITH_PYTHON

2021-05-04 14:29 UTC, sammorris81 commented
All suggestions addressed. Please let me know if there's anything additional.

2021-05-05 07:53 UTC, jmr commented
Thanks for the improvement/fix!

2021-05-05 07:54 UTC, jmr commented
Sorry, one more thing I just thought of. Can you add python back here, so it's still tested, since it now defaults to off??

https://github.com/google/s2geometry/blob/master/.travis.yml#L162

2021-05-05 15:38 UTC, sammorris81 commented
Added -DWITH_PYTHON=ON to the test. Please let me know if there's anything additional you would like.

2021-05-06 12:09 UTC, merged